name: CI

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version to upload'
        required: true

jobs:
  publish:
    uses: ./.github/workflows/callable.publish.yml
    with:
      VERSION: ${{ inputs.VERSION }}